spring:
  rabbitmq:
    host: 127.0.0.1
    password: guest
    port: 5672
    username: guest
    virtual-host: /
    publisher-confirm-type: simple
    publisher-returns: true
    listener:
      simple:
        concurrency: 10
        max-concurrency: 20
        prefetch: 1
        auto-startup: true
        retry:
          enabled: true
        acknowledge-mode: manual

